version: "3.1"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: runwith/get-started:flask
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:5000"
    networks:
      - webnet
  db:
    image: postgres
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # This one doesn't crash it
      # - ./data:/var/lib/postgresql/data
      # - "/home/docker/data:/var/lib/postgresql/data"
      #- "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - webnet
    deploy:
      placement:
        constraints: [node.role == manager]
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet: